### ISSUE TITLE
Why is there a need to differentiate between functions and variables?

### ISSUE THREAD

**Issue by myeffort** [Bruce-Connor/names#16]
Bruce, if you don't mind delving into some details, please explain the reason. Isn't it all a symbol after all?

**Comment by Bruce-Connor** [comment]
Yes, it's all a symbol, but they're not the same thing. A symbol can be both, either, or neither. Elisp is not like Clojure, where the two are the same thing.

If we expand the name of a function where a symbol is being used as a variable (or vice versa), then we'd generate invalid code, so we need to watch out for that.

**Comment by myeffort** [comment]
Thank you for your reply. 

Did I understand you correctly that without type checking, following case constitute invalid code?

    (defvar foo "bar")
    (define-namespace ns-
    (defun foo ())
    (defun baz () (print foo))) ;; => (void-variable baz-foo)

**Comment by Bruce-Connor** [comment]
Yes, if Names didn't differentiate functions and variables, that's exactly
what would happen. :-)
